spring:
  application:
    name: outbox-consumer
  
  # 기본 프로파일 설정
  profiles:
    active: local
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # 자동으로 테이블 생성/업데이트
    show-sql: true
    properties:
      hibernate:
        "[format_sql]": true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          "[time_zone]": UTC

# 서버 설정
server:
  port: 8080
  shutdown: graceful

# 관리 엔드포인트 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: true
