curl -s -X POST http://localhost:8083/connectors \
  -H "Content-Type: application/json" \
  -d '{
    "name": "postgres-sink-cdc-connector",
    "config": {
      "connector.class": "io.debezium.connector.jdbc.JdbcSinkConnector",
      "tasks.max": "1",
      "topics": "mariadb.cloud.users",
      "connection.url": "jdbc:postgresql://a549d1be548d945fbaa811f46bd3b3dd-586480945.ap-northeast-2.elb.amazonaws.com:5432/cloud?tcpKeepAlive=true&socketTimeout=30&connectTimeout=30",
      "connection.username": "skala",
      "connection.password": "Skala25a!23$",
      "table.name.format": "users_cdc",
      "auto.create": "true",
      "auto.evolve": "true",
      "schema.evolution": "basic",
      "quote.identifiers": "false",
      "insert.mode": "upsert",
      "primary.key.mode": "record_key",
      "primary.key.fields": "user_id",
      "delete.enabled": "true",
      "batch.size": "100",
      "hibernate.connection.provider_class": "org.hibernate.connection.C3P0ConnectionProvider",
      "hibernate.c3p0.min_size": "1",
      "hibernate.c3p0.max_size": "5",
      "hibernate.c3p0.acquire_increment": "1",
      "hibernate.c3p0.timeout": "1800",
      "hibernate.c3p0.max_statements": "50",
      "hibernate.c3p0.idle_test_period": "30",
      "hibernate.c3p0.idleConnectionTestPeriod": "30",
      "hibernate.c3p0.maxIdleTime": "300",
      "hibernate.c3p0.maxIdleTimeExcessConnections": "120",
      "hibernate.c3p0.testConnectionOnCheckout": "true",
      "hibernate.c3p0.testConnectionOnCheckin": "false",
      "hibernate.c3p0.preferredTestQuery": "SELECT 1",
      "hibernate.c3p0.validate": "true",
      "errors.tolerance": "all",
      "errors.log.enable": "true",
      "errors.log.include.messages": "true",
      "errors.retry.delay.max.ms": "60000",
      "errors.retry.timeout": "300000",
      "errors.deadletterqueue.topic.name": "dlq-postgresql-sink",
      "errors.deadletterqueue.topic.replication.factor": "1",
      "errors.deadletterqueue.context.headers.enable": "true"
    }
  }' | jq
